version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

  backend:
    build: .
    container_name: notificacao-backend
    ports:
      - '3000:3000'
    depends_on:
      - rabbitmq
    env_file:
      - .env
